### ISSUE TITLE
homebrew install fails with SHA1 mismatch

### ISSUE THREAD

**Issue by reznet** [mefellows/packer-dsc#2]
je185066@WUSJE185066-13F ~/repos/silver/silvervm/00-Packer$ brew install https://raw.githubusercontent.com/mefellows/packer-dsc/master/scripts/packer-provisioner-dsc.rb
###### ################################################################## 100.0%

Warning: You are using a pre-release version of Xcode.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
==> Downloading https://github.com/mefellows/packer-dsc/releases/download/0.0.1-pre-release/darwin_amd64.zip
==> Downloading from https://github-cloud.s3.amazonaws.com/releases/26093664/b1ce7acc-07da-11e6-8c00-d2cf8c871dea.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Cre
###### ################################################################## 100.0%

Warning: SHA1 support is deprecated and will be removed in a future version.
Please switch this formula to SHA256.
Error: SHA1 mismatch
Expected: 99d3a857486770821f71b22482d3df56715cefc0
Actual: 785bc12ce18ad726c5c8a4aac4cf6206c1ecd718
Archive: /Users/je185066/Library/Caches/Homebrew/packer-provisioner-dsc-0.0.1-pre-release.zip
To retry an incomplete download, remove the file above.

**Comment by mefellows** [comment]
Nice to see you over here @reznet  :)

I'll sort this out, in the meanwhile perhaps just download and extract into the Packer plugin dir.

**Comment by mosen** [comment]
Installing via Homebrew now shows:

```
Warning: Calling Hardware.is_64_bit? is deprecated!
Use Hardware::CPU.is_64_bit? instead.
/Users/x/Library/Caches/Homebrew/Formula/packer-provisioner-dsc.rb:7:in `<class:PackerProvisionerDsc>'

Error: Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/Users/x/Library/Caches/Homebrew/Formula/packer-provisioner-dsc.rb:9:in `<class:PackerProvisionerDsc>'
```
Incoming PR for #2 shortly.

**Comment by mefellows** [comment]
Thanks for the fix @mosen. This, obviously, slipped my TODO list ;)
