### ISSUE TITLE
Create a new release executable to cover latest commits & PR's

### ISSUE THREAD

**Issue by Marcus-James-Adams** [mefellows/packer-dsc#6]
Would it be possible to create a new pre-release executable created?
The current version works with packer API v4 and the latest packer 1.5.1 has been upgraded to API V5.
The incorporation of #5 would be a great help at the same time.

**Comment by mefellows** [comment]
I realised I merged #5 and released https://github.com/mefellows/packer-dsc/releases/tag/v0.0.4 but didn't close this. Closing!
